import Footer from "@/components/organisms/Footer";
import "../assets/font/font.css";
import "./globals.css";
import Navbar from "@/components/organisms/Navbar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata = {
	title: "Torino | تورینو",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<ReactQueryProvider>
					<Navbar />
					{children}
					<Footer />
				</ReactQueryProvider>
			</body>
		</html>
	);
}
