import Footer from "@/components/common/Footer";
import "../assets/font/font.css";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
	title: "Torino | تورینو",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<ReactQueryProvider>
					<Navbar />
					{children}
					<Footer />
				</ReactQueryProvider>
				<Toaster/>
			</body>
		</html>
	);
}
